

name: 'project_DBT_GDS'
version: '1.0.0'
config-version: 2


profile: 'prod_snowflake'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]



models:
  project1:
      +materialized: table


